# -*- coding: utf-8 -*-
"""Geographical_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2dzno-yLwWW4wzAFyvWM_YLyoa23zu4
"""

#Library Import
import numpy as np
import pandas as pd

#create ExcelFile object
xls = pd.ExcelFile('/content/Project Data.xlsx')

#access sheets as separate DataFrames
products = pd.read_excel(xls, 'products')
reviews = pd.read_excel(xls, 'reviews')

"""### Work on Reviews Sheet"""

#data view for first 5 rows
reviews.head()

#datasheet shape
print(reviews.shape)

new_reviews = reviews.drop_duplicates()
print(new_reviews.shape)

#Unique values in 'languageCode_1' Column
new_reviews['languageCode_1'].unique()

new_reviews['languageCode'].unique()

#Dictionary to decode 'languageCode_1' Column
lan_country_decode={'en-US':'English-United States','ru-RU':'Russian-Russia','he-IL':'Hebrew-Israel','ar-SA':'Arabic-Saudi Arabia',
                    'ja-JP':'Japanese-Japan','es-MX':'Spanish-Mexico','fr-FR':'French-France','zh-TW':'Chinese-Taiwan',
                    'zh-CN':'Chinese-China','ko-KR':'Korean language-South Korea','de-DE':'German-Germany','pt-BR':'Portuguese-Brazil'}

new_reviews['language'] = new_reviews.apply(lambda x: lan_country_decode[x.languageCode_1].split("-")[0], axis=1)
new_reviews['geographical'] = new_reviews.apply(lambda x: lan_country_decode[x.languageCode_1].split("-")[1], axis=1)

new_reviews.shape

new_reviews.head(5)

new_reviews.to_excel('new_review_location.xlsx', index=False)